# Generated by Django 3.0 on 2021-01-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201227_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_history',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
